services:
  - type: web
    name: restaurant-analytics
    runtime: docker
    plan: free
    dockerfilePath: ./RestaurantAnalytics.Web/Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_CONNECTION
        sync: false
